mod 'puppetlabs-concat', '6.2.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'puppetlabs-stdlib', '6.3.0'
mod 'samuelson-dockeragent'
mod 'puppetlabs-docker'
mod 'puppetlabs-apache'
mod 'puppetlabs-accounts', '6.1.1'
